### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by nspectware** [andreia/laravel-uppy-upload-app#3]
### Discussed in https://github.com/andreia/laravel-uppy-upload-app/discussions/2

<div type='discussions-op-text'>

<sup>Originally posted by **nspectware** September  9, 2021</sup>
Hi Andreia, I'm building an app with a multi-step, tabbed form. I need two instances of Uppy in the same html page to allow separate uploads of images and videos. I tried using different hiddenFields for each instance, but both instances of Uppy show up in the same tab. I'm guessing it's because they both initialize using the same variable name. Is there an easy workaround for this? I can do it the harder way, but I really like the simplicity of your solution.</div>

**Comment by andreia** [comment]
@nspectware Adding support in this PR: https://github.com/TappNetwork/laravel-uppy-s3-multipart-upload/pull/4, so you can use it like this:

```html
<!-- First Uppy instance for image uploads -->
<div class="grid grid-cols-1 md:grid-cols-1">
    <div class="p-6">
        <div class="flex items-center">
            <input type="hidden" name="images" id="images" />
            <x-input.uppy :options="$optionsImages" :hiddenField="$fieldImages" :uploadElementClass="$classImages" />
        </div>
    </div>
</div>

<!-- Second Uppy instance for video uploads -->
<div class="grid grid-cols-1 md:grid-cols-1">
    <div class="p-6">
        <div class="flex items-center">
            <input type="hidden" name="videos" id="videos" />
            <x-input.uppy :options="$optionsVideos" :hiddenField="$fieldVideos" :uploadElementClass="$classVideos" />
        </div>
    </div>
</div>
```

**Comment by nspectware** [comment]
Great! Thank you!
